name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Use the official Cypress GitHub Action
      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          install: true       # Automatically installs dependencies
          runTests: true      # Runs the tests
          browser: chrome     # Optionally specify the browser (default: electron)
