name: Run Cypress Tests with Debugging

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Ensure Cypress binary is properly installed and permissions are set
      - name: Install Cypress
        run: |
          npx cypress install
          chmod +x $(npm bin)/cypress

      # Verify Cypress installation
      - name: Verify Cypress installation
        run: $(npm bin)/cypress --version

      # Run Cypress tests
      - name: Run Cypress tests
        run: $(npm bin)/cypress run --headed --record
        env:
          CYPRESS_baseUrl: https://dev.crowncoinscasino.com/
        continue-on-error: true

      # Capture screenshots and videos for debugging
      - name: Upload Cypress screenshots and videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos

      # Save workflow artifacts
      - name: Upload logs and reports
        uses: actions/upload-artifact@v3
        with:
          name: cypress-logs
          path: cypress/logs
